/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package flightbooking;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import flightbooking.MyProvider;
import flightbooking.MyProvider;
import flightbooking.NationalFlight;
import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ali Ahmed
 */
public class InternationalFlights extends javax.swing.JInternalFrame {

   String url = MyProvider.url;
    public InternationalFlights() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui =(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        Delete = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        flightnumber = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        depairport = new javax.swing.JTextField();
        destairport = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        planeid = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        deptime = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        arrtime = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        bags = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 51, 255));
        setPreferredSize(new java.awt.Dimension(580, 490));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "flight number", "departure airport", "destination airport", "departure time", "arrival time", "plane id", "bags", "weight"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 280));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Delete.setBackground(new java.awt.Color(51, 153, 255));
        Delete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel7.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 110, 30));

        Save.setBackground(new java.awt.Color(51, 153, 255));
        Save.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel7.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 30));

        Edit.setBackground(new java.awt.Color(51, 153, 255));
        Edit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Edit.setForeground(new java.awt.Color(255, 255, 255));
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel7.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 90, 30));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(580, 490));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("flight number");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 20));

        flightnumber.setActionCommand("");
        flightnumber.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));
        flightnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightnumberActionPerformed(evt);
            }
        });
        jPanel6.add(flightnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 150, -1));

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("departure Airport");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 20));

        depairport.setActionCommand("");
        depairport.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));
        depairport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depairportActionPerformed(evt);
            }
        });
        jPanel6.add(depairport, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 150, -1));

        destairport.setActionCommand("");
        destairport.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));
        destairport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destairportActionPerformed(evt);
            }
        });
        jPanel6.add(destairport, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 150, -1));

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("destination Airport");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 20));

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Plane Id");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 90, 20));

        planeid.setActionCommand("");
        planeid.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));
        planeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planeidActionPerformed(evt);
            }
        });
        jPanel6.add(planeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 150, -1));

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("departure Time");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 20));

        deptime.setActionCommand("");
        deptime.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));
        deptime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptimeActionPerformed(evt);
            }
        });
        jPanel6.add(deptime, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, -1));

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Arrival Time");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 90, 20));

        arrtime.setActionCommand("");
        arrtime.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));
        arrtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrtimeActionPerformed(evt);
            }
        });
        jPanel6.add(arrtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 150, -1));

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("Bags");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 90, 20));

        bags.setActionCommand("");
        bags.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));
        bags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagsActionPerformed(evt);
            }
        });
        jPanel6.add(bags, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 150, -1));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Weight");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 90, 20));

        weight.setActionCommand("");
        weight.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        jPanel6.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void flightnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightnumberActionPerformed

    private void depairportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depairportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depairportActionPerformed

    private void destairportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destairportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destairportActionPerformed

    private void planeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planeidActionPerformed

    private void deptimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptimeActionPerformed

    private void arrtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrtimeActionPerformed

    private void bagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bagsActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
       DefaultTableModel tblModel = (DefaultTableModel) jTable.getModel();
    if (jTable.getSelectedRowCount() == 1) {
        int selectedRowIndex = jTable.getSelectedRow();
        String flightNumberToDelete = tblModel.getValueAt(selectedRowIndex, 0).toString();
        tblModel.removeRow(selectedRowIndex);
        Connection conn = null;
        try {
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection(url);

            String deleteQuery = "DELETE FROM InternationalFlight WHERE flightnumber = ?";
            PreparedStatement pstmt = conn.prepareStatement(deleteQuery);
            pstmt.setString(1, flightNumberToDelete);
            int affectedRows = pstmt.executeUpdate();

            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Deleted Successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Deletion failed. Flight number not found in the database.");
            }

        } catch (Exception ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + ex.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception ex) {
                System.err.println(ex);
            }
        }
    } else {
        if (jTable.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Table is empty");
        } else {
            JOptionPane.showMessageDialog(this, "Single row is not selected!!");
        }
    }

    }//GEN-LAST:event_DeleteActionPerformed
//MyProvider m = new MyProvider();
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        
        try {
    String a = flightnumber.getText();
    String b = depairport.getText();
    String c = destairport.getText();
    String d = deptime.getText();
    String e = planeid.getText();
    String f = arrtime.getText();
    int h = Integer.parseInt(bags.getText());
    double i = Double.parseDouble(weight.getText());

    InternationalFlight Nflight = new InternationalFlight(a, b, c, d, f, e, h, i);

    // Check for duplicate primary key
    Connection conn = null;
    boolean isDuplicate = false;
    try {
        Class.forName("org.sqlite.JDBC");
        conn = DriverManager.getConnection(url);

        String checkQuery = "SELECT COUNT(*) FROM InternationalFlight WHERE flightnumber = ?";
        PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
        checkStmt.setString(1, a);
        ResultSet rs = checkStmt.executeQuery();
        if (rs.next()) {
            isDuplicate = rs.getInt(1) > 0;
        }
        rs.close();
        checkStmt.close();

        if (!isDuplicate) {
            String insertQuery = "INSERT INTO InternationalFlight (flightNumber, departureAirport, destinationAirport, departureTime, arrivalTime, planeid, numberOfBags, totalWeight) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(insertQuery);
            pstmt.setString(1, a);
            pstmt.setString(2, b);
            pstmt.setString(3, c);
            pstmt.setString(4, d);
            pstmt.setString(5, f);
            pstmt.setString(6, e);
            pstmt.setInt(7, h);
            pstmt.setDouble(8, i);
            pstmt.executeUpdate();
            pstmt.close();

            JOptionPane.showMessageDialog(null, "Flight saved successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Flight with the same flight number already exists. Flight not saved.");
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + ex.getMessage());
    } finally {
        try {
            if (conn != null) {
                conn.close();
            }
        } catch (Exception ex) {
            System.err.println(ex);
        }
    }

} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + ex.getMessage());
}

    }//GEN-LAST:event_SaveActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
     DefaultTableModel tblModel = (DefaultTableModel) jTable.getModel();
    if (jTable.getSelectedRowCount() == 1) {
        int selectedRowIndex = jTable.getSelectedRow();
        String originalFlightNumber = tblModel.getValueAt(selectedRowIndex, 0).toString(); // Assuming flightnumber is unique

        String a = flightnumber.getText();
        String b = depairport.getText();
        String c = destairport.getText();
        String d = deptime.getText();
        String e = planeid.getText();
        String f = arrtime.getText();
        int h = Integer.parseInt(bags.getText());
        double i = Double.parseDouble(weight.getText());

        // Update the table model
        tblModel.setValueAt(a, selectedRowIndex, 0);
        tblModel.setValueAt(b, selectedRowIndex, 1);
        tblModel.setValueAt(c, selectedRowIndex, 2);
        tblModel.setValueAt(d, selectedRowIndex, 3);
        tblModel.setValueAt(e, selectedRowIndex, 4);
        tblModel.setValueAt(f, selectedRowIndex, 5);
        tblModel.setValueAt(h, selectedRowIndex, 6);
        tblModel.setValueAt(i, selectedRowIndex, 7);

        // Update the database
        Connection conn = null;
        try {
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection(url);

            String updateQuery = "UPDATE InternationalFlight SET flightNumber = ?, departureAirport = ?, destinationAirport = ?, departureTime = ?, arrivalTime = ?, planeid = ?, numberOfBags = ?, totalWeight = ? WHERE flightNumber = ?";
            PreparedStatement pstmt = conn.prepareStatement(updateQuery);

            pstmt.setString(1, a);
            pstmt.setString(2, b);
            pstmt.setString(3, c);
            pstmt.setString(4, d);
            pstmt.setString(5, e);
            pstmt.setString(6, f);
            pstmt.setInt(7, h);
            pstmt.setDouble(8, i);
            pstmt.setString(9, originalFlightNumber);

            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Updated Successfully..");

        } catch (Exception ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Error updating database: " + ex.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception ex) {
                System.err.println(ex);
            }
        }
    } else {
        if (jTable.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Table is empty");
        } else {
            JOptionPane.showMessageDialog(this, "Single row is not selected!!");
        }
    }
    }//GEN-LAST:event_EditActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
Connection conn=null;
        try{
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection(url);
        }catch(Exception ex){
            System.err.println(ex);
        }
        try{
    DefaultTableModel dt =(DefaultTableModel)jTable.getModel();
    dt.setRowCount(0);
    
     Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("SELECT * FROM InternationalFlight");
            
             while (rs.next()){
                Vector v = new Vector();
                 v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));  
                v.add(rs.getInt(7));
                v.add(rs.getDouble(8));
                dt.addRow(v);
                
                
             } }catch(Exception e){
            System.err.println(e.getMessage());}
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
      DefaultTableModel tblModel = (DefaultTableModel)jTable.getModel();
      
      String tblflightnumber =tblModel.getValueAt(jTable.getSelectedRow(),0).toString();
      String tbldepairport =tblModel.getValueAt(jTable.getSelectedRow(),1).toString();
      String tbldestairport =tblModel.getValueAt(jTable.getSelectedRow(),2).toString();
      String tbldeptime =tblModel.getValueAt(jTable.getSelectedRow(),3).toString();
      String tblplaneid =tblModel.getValueAt(jTable.getSelectedRow(),4).toString();
      String tblarrtime =tblModel.getValueAt(jTable.getSelectedRow(),5).toString();
    // Convert bags to int
    int tblbags = Integer.parseInt(tblModel.getValueAt(jTable.getSelectedRow(), 6).toString());
    
    // Convert weight to double
    double tblweight = Double.parseDouble(tblModel.getValueAt(jTable.getSelectedRow(), 7).toString());

      
    flightnumber.setText(tblflightnumber);
    depairport.setText(tbldepairport);
    destairport.setText(tbldestairport);
    deptime.setText(tbldeptime);
    planeid.setText(tblplaneid);
    arrtime.setText(tblarrtime);
    bags.setText(Integer.toString(tblbags));
    weight.setText(Double.toString(tblweight));
    }//GEN-LAST:event_jTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Save;
    private javax.swing.JTextField arrtime;
    private javax.swing.JTextField bags;
    private javax.swing.JTextField depairport;
    private javax.swing.JTextField deptime;
    private javax.swing.JTextField destairport;
    private javax.swing.JTextField flightnumber;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField planeid;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
