/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flightbooking;

import flightbooking.MyProvider;
import flightbooking.User;
import flightbooking.LoginPage;
import javax.swing.JOptionPane;

/**
 *
 * @author Ali Ahmed
 */
public class SignUP extends javax.swing.JFrame {
MyProvider my = new MyProvider();
    public SignUP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUpbutton2 = new javax.swing.JButton();
        loginbutton2 = new javax.swing.JButton();
        passwordtext2 = new javax.swing.JTextField();
        usernametext2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpbutton2.setBackground(new java.awt.Color(0, 102, 204));
        SignUpbutton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SignUpbutton2.setForeground(new java.awt.Color(255, 255, 255));
        SignUpbutton2.setText("Sign Up");
        SignUpbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpbutton2ActionPerformed(evt);
            }
        });
        getContentPane().add(SignUpbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 100, 40));

        loginbutton2.setBackground(new java.awt.Color(0, 102, 204));
        loginbutton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginbutton2.setForeground(new java.awt.Color(255, 255, 255));
        loginbutton2.setText("Login");
        loginbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbutton2ActionPerformed(evt);
            }
        });
        getContentPane().add(loginbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 110, 40));

        passwordtext2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        passwordtext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtext2ActionPerformed(evt);
            }
        });
        getContentPane().add(passwordtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 200, 20));

        usernametext2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        usernametext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametext2ActionPerformed(evt);
            }
        });
        getContentPane().add(usernametext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 200, 20));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flightbooking/icons8_Secure_50px.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 50));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 90, 40));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flightbooking/icons8_Account_50px.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 50, 50));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flightbooking/signupnn.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 340, 620));

        setSize(new java.awt.Dimension(324, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordtext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtext2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtext2ActionPerformed

    private void usernametext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametext2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametext2ActionPerformed

    private void SignUpbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpbutton2ActionPerformed
    try{
    String un = usernametext2.getText();
    String ps = passwordtext2.getText();
     User u = new User(un , ps);
     u.SingUp(un, ps);
     JOptionPane.showMessageDialog(this, "Account Created successfully!");
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, "Error");
    }
    
     
     
    }//GEN-LAST:event_SignUpbutton2ActionPerformed

    private void loginbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbutton2ActionPerformed
       
        new LoginPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginbutton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignUpbutton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loginbutton2;
    private javax.swing.JTextField passwordtext2;
    private javax.swing.JTextField usernametext2;
    // End of variables declaration//GEN-END:variables
}
