/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flightbooking;


/**
 *
 * @author Youssef
 */
public class Ticktsprint extends javax.swing.JFrame {

    /**
     * Creates new form Ticktsprint
     */
    public Ticktsprint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seat1 = new javax.swing.JLabel();
        distn = new javax.swing.JLabel();
        depar = new javax.swing.JLabel();
        Date1 = new javax.swing.JLabel();
        Seat2 = new javax.swing.JLabel();
        Date2 = new javax.swing.JLabel();
        flight2 = new javax.swing.JLabel();
        Pass1 = new javax.swing.JLabel();
        flight1 = new javax.swing.JLabel();
        Pass2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1314, 393));
        setMinimumSize(new java.awt.Dimension(1314, 393));
        setPreferredSize(new java.awt.Dimension(1314, 393));
        getContentPane().setLayout(null);

        seat1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        seat1.setForeground(new java.awt.Color(255, 255, 255));
        seat1.setText("Youssef");
        getContentPane().add(seat1);
        seat1.setBounds(270, 330, 170, 20);

        distn.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        distn.setForeground(new java.awt.Color(255, 255, 255));
        distn.setText("jLabel2");
        getContentPane().add(distn);
        distn.setBounds(470, 130, 330, 120);

        depar.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        depar.setForeground(new java.awt.Color(255, 255, 255));
        depar.setText("jLabel2");
        getContentPane().add(depar);
        depar.setBounds(60, 130, 280, 120);

        Date1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        Date1.setForeground(new java.awt.Color(255, 255, 255));
        Date1.setText("Youssef");
        getContentPane().add(Date1);
        Date1.setBounds(20, 330, 180, 20);

        Seat2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        Seat2.setText("Youssef");
        getContentPane().add(Seat2);
        Seat2.setBounds(1040, 220, 110, 25);

        Date2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        Date2.setText("Youssef");
        getContentPane().add(Date2);
        Date2.setBounds(820, 250, 200, 25);

        flight2.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        flight2.setText("Youssef");
        getContentPane().add(flight2);
        flight2.setBounds(930, 132, 90, 40);

        Pass1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        Pass1.setForeground(new java.awt.Color(255, 255, 255));
        Pass1.setText("Youssef");
        getContentPane().add(Pass1);
        Pass1.setBounds(500, 70, 250, 20);

        flight1.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        flight1.setForeground(new java.awt.Color(255, 255, 255));
        flight1.setText("Youssef");
        getContentPane().add(flight1);
        flight1.setBounds(730, 40, 110, 20);

        Pass2.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        Pass2.setText("Youssef");
        getContentPane().add(Pass2);
        Pass2.setBounds(980, 50, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flightbooking/ticket2.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1400, 444));
        jLabel1.setMinimumSize(new java.awt.Dimension(1400, 444));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1400, 444));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1422, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticktsprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticktsprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticktsprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticktsprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticktsprint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Date1;
    public javax.swing.JLabel Date2;
    public javax.swing.JLabel Pass1;
    public javax.swing.JLabel Pass2;
    public javax.swing.JLabel Seat2;
    public javax.swing.JLabel depar;
    public javax.swing.JLabel distn;
    public javax.swing.JLabel flight1;
    public javax.swing.JLabel flight2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel seat1;
    // End of variables declaration//GEN-END:variables

    private void print() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
